optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

model:
  tokenizer_path: kuelumbus/polyBERT
  ema: True

  params:
    latent_dim: 512 #8
    d_model: 512
    nhead: 8
    dim_feedforward: 2048
    activation: "gelu"
    dropout: 0.0
    norm_first: true
    bias: true
    num_layers: 8

    # alpha: 2.
    alpha: 1.
    beta: 1. #0.1 #0.0001 #
    gamma: 0.000001 #0.0
    temperature: 0.05 #1.0 #



data:
  name: polyone
  path: '../../../../ext_hdd/common/polyone_tokenized_new'
  batch_size: 128
  eval_batch_size: 1024
  size: base


train:
  epochs: 1000
  interval: 1 #10


